name: cicd

on: push
env:
  ARTIFACT: "hello"
jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest

    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
      - run: python hello.py
  job2:
    name: second job
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}.py
